---
title: "Circuit Simulator Evaluation"
author: Rhys Adams

colorlinks: true
urlcolor: blue

fontsize: 12pt
geometry: margin=1in

header-includes:
 - \usepackage{fvextra}
 - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
---
